-- Create link_codes table for Telegram→Web authentication
--
-- Original design had bidirectional flows (web_to_telegram and telegram_to_web).
-- Simplified to only telegram_to_web in migration 20260618000000.
--
-- Flow: bot generates code → user enters it in the dashboard to log in
--
-- Each code:
-- - Is 6 alphanumeric characters
-- - Expires in 2-5 minutes
-- - Can only be used once (used = TRUE)

CREATE TABLE link_codes (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  auth_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  direction TEXT NOT NULL CHECK (direction IN ('web_to_telegram', 'telegram_to_web')),
  expires_at TIMESTAMPTZ NOT NULL,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast lookup of unused codes by code value
CREATE INDEX idx_link_codes_code_unused
  ON link_codes(code, used, expires_at)
  WHERE used = FALSE;

-- Index for cleanup of expired codes
CREATE INDEX idx_link_codes_expires
  ON link_codes(expires_at)
  WHERE used = FALSE;

-- Cleanup job: delete expired codes older than 1 hour
-- (runs on every migration apply, but mostly for manual cleanup)
DELETE FROM link_codes WHERE expires_at < NOW() - INTERVAL '1 hour';

-- Grants
GRANT SELECT, INSERT, UPDATE, DELETE ON link_codes TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

-- RLS (service_role bypasses it, but keep for consistency)
ALTER TABLE link_codes ENABLE ROW LEVEL SECURITY;

-- Authenticated users can read their own link_codes
CREATE POLICY "link_codes_read_own" ON link_codes
  FOR SELECT
  USING (user_id IN (SELECT id FROM users WHERE auth_id = auth.uid()));

-- Any authenticated user can insert (needed for web flow)
CREATE POLICY "link_codes_insert_own" ON link_codes
  FOR INSERT
  WITH CHECK (user_id IN (SELECT id FROM users WHERE auth_id = auth.uid()));

-- Allow updating used flag (for validation)
CREATE POLICY "link_codes_update_own" ON link_codes
  FOR UPDATE
  USING (user_id IN (SELECT id FROM users WHERE auth_id = auth.uid()))
  WITH CHECK (user_id IN (SELECT id FROM users WHERE auth_id = auth.uid()));

COMMENT ON TABLE link_codes IS 'One-time codes for linking Telegram accounts to web accounts. Supports web→telegram (vinculo) and telegram→web (login) flows.';
COMMENT ON COLUMN link_codes.direction IS 'web_to_telegram: code generated by dashboard, validated by bot. telegram_to_web: code generated by bot, validated by dashboard.';
