-- NO-OP: auth_id column was already added by 20260617000000_add_rls_policies.sql
--
-- Migration 20260617000000_add_rls_policies.sql already:
--   1. Added auth_id UUID REFERENCES auth.users(id) ON DELETE SET NULL to users
--   2. Created UNIQUE INDEX idx_users_auth_id ON users(auth_id) WHERE auth_id IS NOT NULL
--   3. Added COMMENT ON COLUMN users.auth_id
--
-- This migration is kept as a no-op to avoid changing migration numbering.
-- Logically, this migration number (17000002) has been superseded by 17000000
-- which was created later in commit order but has an earlier migration number.

-- Migrations that depend on auth_id existing: none (they check IF NOT EXISTS or read the current schema)
-- The service_role GRANT for auth_id is unnecessary (service_role bypasses RLS).
-- The COMMENT was already added by 17000000.
